(function(){
  'use strict';
  const A='../Jedburgh_Town_Trail_Assets/';
  const chapters=[
    ['beginnings','Beginnings and the Medieval Burgh'],['abbey-kings','Abbey, Castle and Scottish Kings'],['border-war','War on the Border'],['reformation','Reformation and Royal Visitors'],['law-ideas','Law, Ideas and Jacobites'],['writers-growth','Writers, Science and Civic Growth'],['modern','War, Remembrance and Modern Jedburgh'],['traditions','Living Traditions']
  ];
  const themeNames={faith:'Faith and Abbey',royal:'Royal Jedburgh',defended:'The Defended Burgh',crime:'Crime and Justice',words:'Words and Writers',minds:'Minds of Jedburgh',civic:'Civic Life and Trade',war:'War and Service',traditions:'Living Traditions'};
  const plaqueNames={
    'newgate':'The Newgate','black-bull-inn':'Black Bull Inn','the-courthouse':'The Courthouse','battle-of-burn-wynd':'Battle of Burn Wynd','james-thomson':'James Thomson','royal-hotel':'Royal Hotel','wordsworths-visit':'Wordsworths’ Visit 1803','spread-eagle-hotel':'Spread Eagle Hotel','ramparts-jedburgh-abbey':'Jedburgh Abbey at the Ramparts','abbey-close':'Abbey Close','abbey-close-jedburgh-abbey':'Jedburgh Abbey at Abbey Close','jedburgh-friary':'Jedburgh Friary','wrens-nest':'Wren’s Nest','jedburgh-castle-jail':'Jedburgh Castle Jail','prince-charlies-house':'Prince Charlie’s House','mary-queen-of-scots-house':'Mary Queen of Scots House','carters-rest':'Carters’ Rest','james-veitch':'James Veitch','mary-somerville':'Mary Somerville','sir-david-brewster':'Sir David Brewster','the-ramparts':'The Ramparts','townhead-port':'Townhead Port','skiprunning-burn':'Skiprunning Burn','canongate-bridge':'Canongate Bridge','public-hall':'Public Hall','jedburgh-public-library':'Jedburgh Public Library','john-ainslie':'John Ainslie','closes':'The Closes','port-house':'Port House','sheriff-shortreed':'Sheriff Shortreed','mary-queen-of-scots-visit':'Mary Queen of Scots Visit','pipers-house':'Piper’s House'};
  const E=(id,sortDate,displayDate,dateStatus,cardType,chapter,title,themes,summary,extra={})=>({id,sortDate,displayDate,dateStatus,cardType,chapter,title,themes,summary,...extra});
  const events=[
    E('ecgred',830,'c. AD 830','traditional','major','beginnings','The beginnings of Jedburgh',['faith','civic'],'According to tradition, Bishop Ecgred founded two settlements beside the Jed Water and established an early place of worship. These communities became the beginnings of Jedburgh.',{people:'Bishop Ecgred',place:'The Glebe',locationId:'the-glebe',image:A+'from%20brochure%20photographs_native/glebe2.png',details:'The surviving evidence does not support an exact foundation year, so the date is deliberately approximate.'}),
    E('gedwearde',1050,'c. 1050','approximate','context','beginnings','Gedwearde: the settlement by the Jed',['civic'],'An early form of the town’s name described a settlement associated with the Jed Water.',{place:'The Glebe',locationId:'the-glebe'}),
    E('cross-burgh',1080,'Medieval period','approximate','supporting','beginnings','A cross-shaped burgh',['civic','defended'],'High Street, Castlegate, Exchange Street and Canongate formed the arms of the burgh. Closes and tofts ran from them, while burns, ports and defensible approaches shaped movement.',{place:'Market Place',locationId:'market-place',plaques:['closes','townhead-port','skiprunning-burn'],details:'This form developed over time; it should not be assigned to a single construction date.'}),
    E('canongate-approach',1100,'12th–16th centuries','approximate','context','beginnings','Canongate Bridge controls the northern approach',['defended','civic'],'The bridge, ford and fortified approach channelled travellers into the Royal Burgh. Later traffic refuges changed its form, but the crossing remained a strategic entrance.',{place:'Canongate Bridge',locationId:'canongate-bridge',plaques:['canongate-bridge']}),
    E('priory',1138,'1138','documented','major','abbey-kings','David I founds Jedburgh Priory',['faith','royal'],'King David I brought Augustinian canons from Beauvais to establish a priory beside the Jed. Jedburgh became an important religious and royal centre.',{people:'David I of Scotland',place:'Jedburgh Abbey',locationId:'abbey',plaques:['ramparts-jedburgh-abbey','abbey-close-jedburgh-abbey'],image:A+'from%20brochure%20photographs_native/abbey2.png',details:'The religious house was raised to abbey status in 1154.'}),
    E('malcolm',1165,'1165','documented','supporting','abbey-kings','Malcolm IV dies at Jedburgh Castle',['royal'],'The young king died at Jedburgh on 9 December, aged about 24. His body was taken to Dunfermline Abbey for burial.',{people:'Malcolm IV',place:'Castle Jail',locationId:'castle-jail',plaques:['jedburgh-castle-jail']}),
    E('william-charter',1204,'c. 1204','approximate','context','abbey-kings','William the Lion at Jedburgh',['royal'],'A surviving royal charter was issued at Jedburgh, demonstrating the burgh’s place in the travelling royal court.',{people:'William I',place:'Jedburgh'}),
    E('alexander-court',1229,'1226–1229','documented','supporting','abbey-kings','Alexander II’s court meets at Jedburgh',['royal'],'Royal charters record Alexander II and his court at Jedburgh in 1226 and again on 28 March 1229.',{people:'Alexander II',place:'Jedburgh'}),
    E('alexander-negotiations',1258,'1258','documented','supporting','abbey-kings','A young king and a struggle for power',['royal'],'Jedburgh hosted important negotiations involving the young Alexander III and rival interests seeking control of his government.',{people:'Alexander III',place:'Jedburgh'}),
    E('royal-birth',1264,'1264','documented','supporting','abbey-kings','A prince is born at Jedburgh',['royal'],'Queen Margaret gave birth at Jedburgh to Alexander, the future Prince of Scotland and heir of Alexander III.',{people:'Alexander III; Queen Margaret; Alexander, Prince of Scotland',place:'Jedburgh'}),
    E('royal-wedding',1285,'14 October 1285','documented','major','abbey-kings','A royal wedding at the Abbey',['royal','faith'],'Alexander III married Yolande de Dreux at Jedburgh Abbey. Celebrations continued at the castle, placing the town at the centre of a great royal occasion.',{people:'Alexander III; Yolande de Dreux',place:'Jedburgh Abbey',locationId:'abbey',plaques:['abbey-close'],image:A+'from%20brochure%20photographs_native/alexanders_wedding.png',details:'A famous apparition story is associated with the wedding, but it belongs to tradition rather than the documented ceremony.'}),
    E('succession',1286,'1286','documented','context','abbey-kings','Alexander III’s death changes Scotland',['royal','defended'],'The king’s accidental death created a succession crisis that led towards the Wars of Independence.',{place:'Jedburgh Abbey',locationId:'abbey'}),
    E('edward-invasion',1296,'1296','documented','supporting','abbey-kings','Edward I passes through Jedburgh',['royal','defended'],'During his invasion of Scotland, Edward I’s itinerary took him to Jedburgh, away from the town and then back again before he continued north.',{people:'Edward I of England',place:'Jedburgh'}),
    E('abbey-plundered',1305,'1305','documented','major','border-war','The Abbey is wrecked and plundered',['defended','faith'],'English forces under Sir Richard Hastings attacked Jedburgh Abbey. Further ravaging in 1410, 1416 and 1464 showed the cost of the town’s exposed Border position.',{place:'Jedburgh Abbey',locationId:'abbey',image:A+'from%20brochure%20photographs_native/page_03_jedburgh_abbey.png'}),
    E('bruce-visit',1321,'30 September 1321','documented','supporting','border-war','Robert the Bruce at Jedburgh',['royal','defended'],'Robert I is recorded at Jedburgh while travelling towards Berwick and dealing with affairs on the March.',{people:'Robert I — Robert the Bruce',place:'Jedburgh'}),
    E('castle-destroyed',1409,'1409','documented','major','border-war','Jedburgh Castle is deliberately destroyed',['defended','royal'],'Regent Albany ordered the castle demolished so it could no longer be held by English forces. The high ground later became the site of the town’s prison.',{place:'Castle Jail',locationId:'castle-jail',plaques:['jedburgh-castle-jail'],image:A+'from%20brochure%20photographs_native/castle_jail.png'}),
    E('james-ii',1452,'Late February 1452','documented','supporting','border-war','James II enters Douglas country',['royal','defended'],'After killing William, Earl of Douglas, James II moved rapidly into Douglas territory. He was at Jedburgh near the end of February before continuing towards Lochmaben and Dumfries.',{people:'James II',place:'Jedburgh'}),
    E('james-iii',1467,'18 January 1467','documented','context','border-war','James III’s charter at Jedworth',['royal'],'A Great Seal charter explicitly records the king at Jedworth, preserving the historic form of the town’s name.',{people:'James III',place:'Jedburgh'}),
    E('greyfriars',1470,'15th century','approximate','supporting','border-war','The Greyfriars settle in Jedburgh',['faith'],'Sir Andrew Ker provided a site for a Franciscan community involved in teaching, healing and horticulture.',{place:'Jedburgh Friary',locationId:'jedburgh-friary',plaques:['jedburgh-friary']}),
    E('james-iv-1508',1508,'4 December 1508','documented','context','border-war','James IV at Jedburgh',['royal'],'The king’s presence in Jedburgh is documented three years before his better-known confrontation with the Turnbulls.',{people:'James IV',place:'Jedburgh'}),
    E('james-iv-justice',1511,'8 November 1511','documented','supporting','border-war','James IV calls the Turnbulls to account',['royal','crime'],'James IV came to impose royal justice on the troublesome Turnbulls of Rulewater. Leading members of the family were brought to Jedburgh to submit to him.',{people:'James IV',place:'Jedburgh'}),
    E('surrey',1523,'1523','documented','major','border-war','Surrey burns Jedburgh',['defended'],'English forces attacked the Abbey and town. A contemporary report described six defensive towers destroyed.',{place:'Jedburgh Abbey',locationId:'abbey',image:A+'from%20brochure%20photographs_native/rough_wooing.png'}),
    E('james-v',1526,'1526','documented','supporting','border-war','James V attends a Justice Ayre',['royal','crime'],'The young James V attended a Justice Ayre at Jedburgh while under the Earl of Angus’s control. An attempt to free him on the return journey led to the Battle of Melrose, also called Darnick.',{people:'James V; Earl of Angus',place:'Jedburgh'}),
    E('rough-wooing',1544,'1544–1545','documented','major','border-war','The Rough Wooing devastates the town',['defended','faith'],'Forces led by Sir Ralph Ewer and the Earl of Hertford burned the Abbey and town during Henry VIII’s campaign to force a royal marriage.',{place:'The Glebe',locationId:'the-glebe',plaques:['the-ramparts'],image:A+'from%20brochure%20photographs_native/ramparts2.png'}),
    E('french-defence',1548,'1548–1549','documented','supporting','border-war','French troops defend Jedburgh',['defended'],'General d’Essé constructed gun platforms beside the Abbey—the earthworks now known as the Ramparts—and French reinforcement helped end English occupation.',{place:'The Ramparts',locationId:'ramparts',plaques:['the-ramparts']}),
    E('panter',1552,'1552','documented','supporting','reformation','Bishop Panter at David’s Tower',['faith'],'Bishop David Panter’s residence stood within the Abbey precinct, recalling the close relationship between church, learning and royal government.',{people:'David Panter',place:'Abbey Close',locationId:'abbey-close',plaques:['abbey-close']}),
    E('reformation',1560,'1560','documented','major','reformation','Reformation ends the monastic Abbey',['faith'],'The canons could no longer recruit after the Scottish Reformation. Parts of the great building continued in use as Jedburgh’s parish church.',{place:'Jedburgh Abbey',locationId:'abbey',plaques:['ramparts-jedburgh-abbey'],image:A+'from%20brochure%20photographs_native/reformation.png'}),
    E('mary',1566,'October–November 1566','documented','major','reformation','Mary, Queen of Scots in Jedburgh',['royal','crime'],'Mary came to conduct a Justice Ayre and remained for about a month. Her demanding ride to Hermitage Castle was followed by severe illness and recovery in Jedburgh.',{people:'Mary, Queen of Scots',place:'Mary Queen of Scots House',locationId:'mary-queen-of-scots-house',plaques:['mary-queen-of-scots-house','mary-queen-of-scots-visit','spread-eagle-hotel'],image:A+'from%20brochure%20photographs_native/mary_queen2.png',details:'Her connection with the Spread Eagle is reputed rather than firmly documented.'}),
    E('redeswire',1575,'1575','documented','context','reformation','The Raid of the Redeswire',['defended','traditions'],'A major Border confrontation later became part of Jedburgh’s remembered history, including its 400th anniversary in 1975.',{place:'Public Hall',locationId:'public-hall'}),
    E('james-justice',1588,'April 1588','documented','supporting','reformation','James VI dispenses Border justice',['royal','crime'],'The king travelled to Jedburgh and held justice against Border reivers, echoing the royal judicial role performed by his mother 22 years earlier.',{people:'James VI',place:'Jedburgh'}),
    E('burn-wynd',1601,'1601','documented','supporting','law-ideas','The Battle of Burn Wynd',['crime'],'A Turnbull feud was pursued into the burgh and Sir Thomas Ker was killed, exposing the violence that could cross the town’s defended boundary.',{place:'Burn Wynd',locationId:'market-place',plaques:['battle-of-burn-wynd']}),
    E('crowns',1603,'1603','documented','context','law-ideas','The Union of the Crowns',['civic','defended'],'The trail presents the shared monarchy as the end of sustained cross-Border warfare and the beginning of increased trade.',{place:'The Glebe',locationId:'the-glebe'}),
    E('pipers',1604,'1604','documented','supporting','law-ideas','Piper’s House and the Ainslies',['civic','traditions'],'The marriage lintel of Adam and Janet Ainslie survives on a building later associated with Jedburgh’s hereditary burgh pipers.',{people:'Adam and Janet Ainslie',place:'Piper’s House',locationId:'pipers-house',plaques:['pipers-house']}),
    E('wrens-gift',1610,'1610','documented','supporting','law-ideas','A royal gift at Wren’s Nest',['royal'],'James VI granted the site to Alexander, Earl of Home. The building later served changing educational and civic purposes.',{people:'James VI; Alexander, Earl of Home',place:'Abbey Close',locationId:'abbey-close',plaques:['wrens-nest']}),
    E('lex-rex',1644,'1644','documented','major','law-ideas','Samuel Rutherford writes Lex, Rex',['minds','crime'],'The former Jedburgh pupil argued that rulers derive authority from law and citizens. The restored monarchy burned the book and accused Rutherford of treason; he died before trial.',{people:'Samuel Rutherford',place:'Public Hall',locationId:'public-hall',plaques:['public-hall']}),
    E('union-trade',1707,'1707','documented','context','law-ideas','Union changes Border trade',['civic'],'The trail links new taxes to decline in local tanning and malting and to later emigration.',{place:'The Glebe',locationId:'the-glebe'}),
    E('thomson',1720,'1700–1748','documented','supporting','law-ideas','James Thomson and “Rule, Britannia!”',['words'],'The Jedburgh-educated poet wrote The Seasons and the words published as “Rule, Britannia!” in 1740.',{people:'James Thomson',place:'High Street',locationId:'high-street',plaques:['james-thomson']}),
    E('black-bull',1726,'1726','documented','supporting','law-ideas','Murder at the Black Bull Inn',['crime'],'Sir Gilbert Elliot of Stobs killed Colonel Stewart at the inn and later received a pardon.',{people:'Sir Gilbert Elliot of Stobs; Colonel Stewart',place:'Canongate',locationId:'canongate',plaques:['black-bull-inn']}),
    E('charlie',1745,'6–7 November 1745','traditional','major','law-ideas','Bonnie Prince Charlie stays in Jedburgh',['royal'],'During the Jacobite advance into England, Charles Edward Stuart spent the night in Jedburgh. The surviving Castlegate house is traditionally associated with his stay.',{people:'Charles Edward Stuart',place:'Prince Charlie’s House',locationId:'prince-charlies-house',plaques:['prince-charlies-house'],image:A+'from%20brochure%20photographs_native/prince_charlie2.png'}),
    E('ainslie',1770,'1745–1828','documented','supporting','writers-growth','John Ainslie maps Scotland',['minds'],'The Jedburgh-born surveyor, mapmaker and engraver worked across Scotland and on the Forth and Clyde Canal project.',{people:'John Ainslie',place:'Jedburgh',plaques:['john-ainslie']}),
    E('newgate',1756,'1756','documented','supporting','writers-growth','Construction begins on the Newgate',['crime','civic'],'A courthouse and prison cells began to replace the old Tolbooth. The building later acquired its prominent spire.',{place:'Newgate',locationId:'newgate',plaques:['newgate'],image:A+'from%20brochure%20photographs_native/newgate2.png'}),
    E('shortreed',1790,'1762–1829','documented','supporting','writers-growth','Sheriff Shortreed preserves Border stories',['words'],'Shortreed and Walter Scott collected ballads, stories and legends later used in the Minstrelsy of the Scottish Border.',{people:'Robert Shortreed; Walter Scott',place:'Loupin’-on Stane',locationId:'loupin-on-stane',plaques:['sheriff-shortreed']}),
    E('burns-harrow',1787,'1787','documented','supporting','writers-growth','Robert Burns at the Harrow Inn',['words'],'Robert Burns lodged near the Harrow Inn and became a Freeman of Jedburgh during his Borders tour.',{people:'Robert Burns',place:'Canongate',locationId:'canongate'}),
    E('jedburgh-minds',1781,'1771–1872','documented','major','writers-growth','A remarkable community of scientific minds',['minds'],'James Veitch made telescopes at Inchbonny; Mary Somerville became a pioneering mathematician and writer; and David Brewster transformed optics and invented the kaleidoscope.',{people:'James Veitch; Mary Somerville; David Brewster',place:'Abbey Close',locationId:'abbey-close',plaques:['james-veitch','mary-somerville','sir-david-brewster','carters-rest'],image:A+'created%20graphics/mary_somerville.png'}),
    E('scott-court',1793,'1791–1793','documented','supporting','writers-growth','A tower disappears; Scott enters court',['crime','civic'],'Kirkwynd Tower was demolished in 1791. Two years later, Walter Scott appeared as a defence lawyer in Jedburgh’s court.',{people:'Walter Scott',place:'Sheriff Court',locationId:'sheriff-court',plaques:['the-courthouse']}),
    E('wordsworth',1803,'1803','documented','supporting','writers-growth','Wordsworth, Dorothy and Scott meet',['words'],'William and Dorothy Wordsworth stayed at Abbey Close and were visited by Walter Scott.',{people:'William Wordsworth; Dorothy Wordsworth; Walter Scott',place:'Abbey Close',locationId:'abbey-close',plaques:['wordsworths-visit']}),
    E('civic-buildings',1812,'1812–1823','documented','major','writers-growth','Jedburgh’s new civic institutions',['civic','crime'],'French prisoners built the Council House in 1812; Trinity Church opened in 1818; and work began on a Howard-inspired prison in 1820, described as built in 1823.',{place:'Sheriff Court',locationId:'sheriff-court',plaques:['the-courthouse'],image:A+'created%20graphics/trinity_church_banner.png',details:'The dates distinguish the start of prison construction from the date given for the completed building.'}),
    E('victorian-growth',1861,'1861–1901','documented','major','writers-growth','Victorian Jedburgh expands',['civic'],'New court accommodation, bank premises, schools, libraries and public buildings reshaped the centre. After the Corn Exchange fire of 1898, Port House, the present library and Public Hall formed a renewed civic group.',{place:'Public Hall',locationId:'public-hall',plaques:['port-house','jedburgh-public-library','public-hall'],image:A+'from%20brochure%20photographs_native/public_hall2.png'}),
    E('victoria-visit',1867,'23 August 1867','documented','supporting','writers-growth','Queen Victoria visits Jedburgh',['royal','civic'],'During her stay with the Duke and Duchess of Roxburghe at Floors Castle, Queen Victoria visited Jedburgh. Her party dined at the hotel later renamed the Royal Hotel in connection with the visit.',{people:'Queen Victoria',place:'Canongate',locationId:'canongate',plaques:['royal-hotel']}),
    E('abbey-church',1875,'1875','documented','supporting','writers-growth','The Abbey ceases to be the parish church',['faith'],'Worship transferred to the new church across the river, allowing later care and restoration of the medieval fabric.',{place:'Jedburgh Abbey',locationId:'abbey'}),
    E('education-rugby',1883,'1882–1884','documented','supporting','writers-growth','Education, rugby and public reading',['minds','traditions'],'The Grammar School moved in 1882, Ned Haig devised Rugby Sevens in 1883, and Andrew Carnegie opened the High Street library in 1884.',{people:'Ned Haig; Andrew Carnegie',place:'Riverside Walk',locationId:'riverside-walk',plaques:['carters-rest','jedburgh-public-library']}),
    E('war-heroes',1914,'1914–1920','documented','major','modern','Courage, survival and remembrance',['war'],'George Stuart Henderson earned the MC, two DSOs and a posthumous VC. John Daykins re-enlisted, won the VC and returned to a Jedburgh homecoming. Their stories sit among many local losses.',{people:'George Stuart Henderson; John Daykins',place:'War Memorial',locationId:'war-memorial',image:A+'from%20brochure%20photographs_native/callant.png'}),
    E('prince-george',1930,'1930','documented','supporting','modern','Prince George visits Queen Mary’s House',['royal'],'Prince George, Duke of Kent, visited Mary Queen of Scots’ House accompanied by Provost Mabon.',{people:'Prince George, Duke of Kent; Provost Mabon',place:'Mary Queen of Scots House',locationId:'mary-queen-of-scots-house'}),
    E('u559',1942,'30 October–13 December 1942','documented','major','modern','The U-559 codebooks',['war','minds'],'Tony Fasson, Colin Grazier and Tommy Brown recovered code material from a sinking U-boat. Fasson and Grazier drowned; the material helped Bletchley Park read renewed U-boat traffic.',{people:'Tony Fasson; Colin Grazier; Tommy Brown',place:'War Memorial',locationId:'war-memorial',image:A+'created%20graphics/U559.png'}),
    E('u-boats',1943,'24 May 1943','documented','context','modern','U-boats withdraw from the North Atlantic',['war'],'The trail connects the recovered material with the Allied advantage that contributed to the German withdrawal.',{place:'War Memorial',locationId:'war-memorial'}),
    E('george-vi',1947,'1947','documented','supporting','modern','George VI and Queen Elizabeth visit',['royal'],'King George VI and Queen Elizabeth visited Jedburgh. The supplied royal chronology records the visit but gives no further details of their programme.',{people:'King George VI; Queen Elizabeth',place:'Jedburgh'}),
    E('elizabeth-1962',1962,'1962','documented','supporting','modern','Elizabeth II received on the Ramparts',['royal','civic'],'Provost S. G. Ewing introduced ten townspeople, Fiona Fraser presented a bouquet, and the Queen visited the museum at Queen Mary’s House and signed its visitors’ book.',{people:'Queen Elizabeth II; Provost S. G. Ewing; Fiona Fraser',place:'The Ramparts',locationId:'ramparts'}),
    E('elizabeth-1978',1978,'4 July 1978','documented','supporting','modern','The Queen and Prince Philip visit',['royal'],'Elizabeth II and Prince Philip made a royal visit to Jedburgh, captured on film by Rob Cockburn.',{people:'Queen Elizabeth II; Prince Philip',place:'Jedburgh'}),
    E('charles-1995',1995,'3 July 1995','approximate','supporting','modern','Prince Charles meets the Callant',['royal','traditions'],'Charles, Prince of Wales, visited during the Jethart Callant Festival and met the Callant. A contemporary preview joked about posters announcing “Prince Charles to meet Callant”.',{people:'Charles, Prince of Wales',place:'Jedburgh',details:'The supplied chronology marks the exact day with an asterisk, so it is shown as an approximate date.'}),
    E('charles-1999',1999,'1999','documented','supporting','modern','Traditional skills at Harestanes',['royal','civic'],'As Duke of Rothesay, Prince Charles visited the Wood School at Harestanes, tried pole-lathe woodturning and discussed forestry, furniture and traditional skills.',{people:'Prince Charles, Duke of Rothesay',place:'Harestanes'}),
    E('anne-2006',2006,'April 2006','documented','supporting','modern','Princess Anne opens the bandstand',['royal','civic'],'Anne, Princess Royal, officially opened the Jedforest Bandstand—the last Royal Family visit to Jedburgh recorded by the Royal Household before 2026.',{people:'Anne, Princess Royal',place:'Jedforest Bandstand'}),
    E('redeswire-remembered',1975,'5 July 1975','documented','supporting','traditions','Redeswire remembered in modern Jedburgh',['traditions'],'Callant Bruce Craigie and Lord Home took part as the 400th anniversary approached, while the same surviving account recalls the town’s dance-hall culture.',{people:'Bruce Craigie; Lord Home',place:'Public Hall',locationId:'public-hall'}),
    E('charles-king',2026,'2 July 2026','documented','supporting','traditions','Charles III returns as King',['royal','traditions'],'The King visited Jedforest Bandstand and Park, Jed Shed, Market Square and local businesses, watched the Callant cavalcade and started the Handba’.',{people:'Charles III',place:'Market Place',locationId:'market-place'}),
    E('living',2027,'Present day','documented','major','traditions','Traditions that still animate the town',['traditions'],'The Jethart Callant’s Festival, the Canongate ford ride, Handba’, Jed-Forest rugby and the “Three Nines” keep Jedburgh’s past active in the life of the town.',{place:'War Memorial',locationId:'war-memorial',image:A+'from%20brochure%20photographs_native/callant.png'})
  ].sort((a,b)=>a.sortDate-b.sortDate);

  const timeline=document.getElementById('timeline'),filter=document.getElementById('themeFilter'),plaquesOnly=document.getElementById('plaquesOnly'),count=document.getElementById('resultsCount'),noResults=document.getElementById('noResults'),tracker=document.getElementById('chapterTracker'),jump=document.getElementById('chapterJump');
  const escape=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const statusNames={documented:'Documented',approximate:'Approximate date',traditional:'Traditional account',disputed:'Date under review'};
  const imageHtml=e=>e.image?`<img class="event-image" src="${e.image}" alt="" loading="lazy">`:'';
  function cardHtml(e){
    const plaqueText=(e.plaques||[]).map(id=>plaqueNames[id]||id).join(', ');
    const meta=[e.people?`<span><strong>People:</strong> ${escape(e.people)}</span>`:'',e.place?`<span><strong>Place:</strong> ${escape(e.place)}</span>`:''].filter(Boolean).join('');
    return `<article class="event ${e.cardType}" id="${e.id}" data-themes="${e.themes.join(' ')}" data-plaques="${(e.plaques||[]).join(' ')}"><div>${imageHtml(e)}</div><div class="event-body"><div class="date-row"><span class="date">${escape(e.displayDate)}</span><span class="status ${e.dateStatus}">${statusNames[e.dateStatus]}</span><span class="type-label">${e.cardType}</span></div><h3>${escape(e.title)}</h3><div class="date-row">${e.themes.map(t=>`<span class="theme-chip">${themeNames[t]}</span>`).join('')}</div><p class="summary">${escape(e.summary)}</p>${meta?`<div class="meta-row">${meta}</div>`:''}${plaqueText?`<p class="plaque-list"><strong>Related plaque${e.plaques.length>1?'s':''}:</strong> ${escape(plaqueText)}</p>`:''}<div class="link-row">${e.locationId?`<a class="place-link" href="location.html?id=${encodeURIComponent(e.locationId)}">Visit this trail stop</a>`:''}${e.details?`<button class="details-toggle" type="button" aria-expanded="false" aria-controls="details-${e.id}">Read more</button>`:''}</div>${e.details?`<p class="event-details" id="details-${e.id}" hidden>${escape(e.details)}</p>`:''}</div></article>`;
  }
  function render(){
    const theme=filter.value,onlyPlaques=plaquesOnly.checked;
    const visible=events.filter(e=>(theme==='all'||e.themes.includes(theme))&&(!onlyPlaques||(e.plaques&&e.plaques.length)));
    timeline.innerHTML=chapters.map(([key,name])=>{const items=visible.filter(e=>e.chapter===key);return items.length?`<section class="chapter" id="chapter-${key}" data-chapter="${escape(name)}"><header class="chapter-heading"><p>Chapter</p><h2>${escape(name)}</h2></header>${items.map(cardHtml).join('')}</section>`:''}).join('');
    count.textContent=`Showing ${visible.length} of ${events.length} stories`;
    noResults.hidden=visible.length!==0;
    timeline.querySelectorAll('.details-toggle').forEach(button=>button.addEventListener('click',()=>{const panel=document.getElementById(button.getAttribute('aria-controls'));const open=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',String(!open));button.textContent=open?'Read more':'Show less';panel.hidden=open;}));
    observeChapters();
  }
  function reset(){filter.value='all';plaquesOnly.checked=false;render();}
  chapters.forEach(([key,name])=>jump.add(new Option(name,`chapter-${key}`)));
  jump.addEventListener('change',()=>{const target=document.getElementById(jump.value);if(target)target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});jump.value='';});
  filter.addEventListener('change',render);plaquesOnly.addEventListener('change',render);document.getElementById('resetFilters').addEventListener('click',reset);document.getElementById('emptyReset').addEventListener('click',reset);
  let observer;
  function observeChapters(){if(observer)observer.disconnect();observer=new IntersectionObserver(entries=>{const active=entries.filter(e=>e.isIntersecting).sort((a,b)=>a.boundingClientRect.top-b.boundingClientRect.top)[0];if(active)tracker.textContent=active.target.dataset.chapter;},{rootMargin:'-10% 0px -70%',threshold:0});document.querySelectorAll('.chapter').forEach(section=>observer.observe(section));}
  const backTop=document.getElementById('backTop'),progress=document.getElementById('readingProgress');
  function onScroll(){const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${max>0?Math.min(100,scrollY/max*100):0}%`;backTop.classList.toggle('show',scrollY>600)}
  addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',onScroll,{passive:true});backTop.addEventListener('click',()=>scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}));
  render();onScroll();
})();
